// Writes src/version.ts at build time with the current git short-SHA and an
// ISO build timestamp. Generated, so the stamp can never drift from the code.
// Runs automatically before `npm run build` via the "prebuild" script.
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

let commit = 'local';
try {
  commit = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString().trim() || 'local';
} catch (_) { /* not a git repo (e.g. CI artifact) -> leave as 'local' */ }

const buildDate = new Date().toISOString();
const out =
`// AUTO-GENERATED by scripts/generate-version.js at build time. Do not edit.
export const APP_VERSION = {
  commit: '${commit}',
  buildDate: '${buildDate}'
};
`;
const target = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(target, out);
console.log('Wrote', target, '->', commit, buildDate);
